version: '3.8'

services:
  backend:
    image: vghuy/midterm-api:${TAG:-latest}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/midterm_db
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - app_net
    # labels: ... (nếu dùng Traefik sau này)

  mongodb:
    image: mongo:6.0
    volumes:
      - db_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx-config:/etc/nginx/conf.d   # Dùng Docker Config hoặc volume tốt hơn
    networks:
      - app_net
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db_data:
  nginx-config:   # Thêm volume này

networks:
  app_net:
    driver: overlay
    attachable: true