name: Docker Swarm CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/midterm-api:latest

      - name: Copy stack file to Manager Node
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-stack.yml,nginx.conf"
          target: "/home/ubuntu/"

      - name: Deploy to Swarm Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
            sudo docker stack deploy -c docker-stack.yml final_app
